### PR TITLE
Wrapped all iOS plugin actions into background threads in order not to block the main thread

### PR DESCRIPTION
**Pull request by IvanKarpan**
Recommended course of action by Cordova developers

### CODE REVIEW

**Comment by IvanKarpan** [comment]
Please merge this, I will push another one with Flurry 6.0.0 support

**Comment by jfpsf** [comment]
Done

**Comment by IvanKarpan** [comment]
Thanks, 6.0.0 coming right up

**Comment by IvanKarpan** [comment]
Oh, it actually merged those commits as well :-/

Oh well, good

Thanks for the plugin! :)

**Pull request merged**
